### PR TITLE
carpeta package

### PR DESCRIPTION
**Pull request by ghost**
solo hacia falta la carpeta package, donde se encuentran los archivos estaticos los cuales permiten visualizar los ejemplos de una manera agradable.

### CODE REVIEW

**Comment by RobertinoValue** [comment]
The `package` folder is not included because it is ignored (with `site/package`) in the projects' `.gitignore`file.
So that git doesn't have to track changes to files in this folder. This keeps the repo size down.

The `*.css` files can be compiled from the `*.styl` source files, and the `tuktuk.js` file can be compiled from the `*.coffee` source files.

**Comment by ghost** [comment]
ok...

**Comment by soyjavi** [comment]
It's incorrect... package-tuktuk it's a gitmodule

**Comment by RobertinoValue** [comment]
OK, I found it here : https://github.com/soyjavi/package-tuktuk
If what I wrote is incorrect, then why not delete the sources folder from this repo?

**Pull request closed without merging**
